SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5E22CEC92125910C}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{5E22CEC92C854063}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{61B2A3760BDE41B0}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{61B2A3760ED65DBC}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{61B2A3763291B06B}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{61B4AA57E8494190}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{61B2A3763291B06B}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{61B4AA57ECD4520A}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{61B2A3763291B06B}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6556A2FE10697152}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6556A2FFDA3E53E5}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{6556A2FFDA3E5050}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6556A2FFC438824C}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{6556A2FFC43882D0}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6556B93806ADFA5D}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{6556B93806ADFA2E}" {
       m_bIncludeInLootSpawning 0
      }
     }
    }
   }
  }
 }
}