// Runtime loader for pre-generated loot table config
// Load the config generated by TW_LootTableGeneratorPlugin in Workbench

class TW_LootTableLoader
{
	protected static const string CONFIG_PATH = "$profile:loot_config.json";

	//------------------------------------------------------------------------------------------------
	// Load loot table from config file
	// Returns true if loaded successfully, false if should fall back to runtime generation
	static bool LoadFromConfig(
		out map<SCR_EArsenalItemType, ref array<ref TW_LootConfigItem>> lootTable,
		out set<string> globalItems,
		out map<string, SCR_EArsenalItemType> resourceTypeMap)
	{
		// Check if config exists
		SCR_JsonLoadContext loadContext = new SCR_JsonLoadContext();
		if (!loadContext.LoadFromFile(CONFIG_PATH))
		{
			Print("[TW_LootLoader] Config file not found, will generate at runtime", LogLevel.NORMAL);
			return false;
		}

		// Parse config
		ref TW_LootTableConfig config;
		if (!loadContext.ReadValue("", config))
		{
			Print("[TW_LootLoader] Failed to parse config file", LogLevel.ERROR);
			return false;
		}

		if (!config || !config.Categories)
		{
			Print("[TW_LootLoader] Config is empty or invalid", LogLevel.ERROR);
			return false;
		}

		Print(string.Format("[TW_LootLoader] Loading config version %1 (generated %2)", config.Version, config.GeneratedDate), LogLevel.NORMAL);

		// Build type name map
		array<SCR_EArsenalItemType> itemTypes = {};
		SCR_Enum.GetEnumValues(SCR_EArsenalItemType, itemTypes);

		ref map<string, SCR_EArsenalItemType> typeNameMap = new map<string, SCR_EArsenalItemType>();
		for (int i = 0; i < itemTypes.Count(); i++)
		{
			string name = SCR_Enum.GetEnumName(SCR_EArsenalItemType, itemTypes[i]);
			typeNameMap.Set(name, itemTypes[i]);
		}

		// Process each category
		int totalItems = 0;
		int enabledItems = 0;
		int skippedItems = 0;

		for (int c = 0; c < config.Categories.Count(); c++)
		{
			string categoryName = config.Categories.GetKey(c);
			ref array<ref TW_GeneratedLootItem> items = config.Categories.GetElement(c);

			if (!typeNameMap.Contains(categoryName))
			{
				Print(string.Format("[TW_LootLoader] Unknown category: %1, skipping", categoryName), LogLevel.WARNING);
				continue;
			}

			SCR_EArsenalItemType itemType = typeNameMap.Get(categoryName);

			if (!lootTable.Contains(itemType))
				lootTable.Set(itemType, new array<ref TW_LootConfigItem>());

			ref array<ref TW_LootConfigItem> categoryLoot = lootTable.Get(itemType);

			for (int i = 0; i < items.Count(); i++)
			{
				TW_GeneratedLootItem genItem = items[i];
				totalItems++;

				// Skip disabled items
				if (!genItem.isEnabled)
				{
					skippedItems++;
					continue;
				}

				// Skip items with 0 chance
				if (genItem.chanceToSpawn <= 0)
				{
					skippedItems++;
					continue;
				}

				// Validate resource exists
				Resource resource = Resource.Load(genItem.resourceName);
				if (!resource.IsValid())
				{
					Print(string.Format("[TW_LootLoader] Invalid prefab: %1", genItem.resourceName), LogLevel.WARNING);
					skippedItems++;
					continue;
				}

				// Create config item
				ref TW_LootConfigItem configItem = new TW_LootConfigItem();
				configItem.resourceName = genItem.resourceName;
				configItem.chanceToSpawn = genItem.chanceToSpawn;
				configItem.randomSpawnCount = genItem.maxSpawnCount;
				configItem.isEnabled = true;

				categoryLoot.Insert(configItem);
				globalItems.Insert(genItem.resourceName);
				resourceTypeMap.Set(genItem.resourceName, itemType);
				enabledItems++;
			}
		}

		Print(string.Format("[TW_LootLoader] Loaded %1 items (%2 enabled, %3 skipped)", totalItems, enabledItems, skippedItems), LogLevel.NORMAL);

		return enabledItems > 0;
	}

	//------------------------------------------------------------------------------------------------
	// Check if config file exists
	static bool HasConfig()
	{
		SCR_JsonLoadContext loadContext = new SCR_JsonLoadContext();
		return loadContext.LoadFromFile(CONFIG_PATH);
	}

	//------------------------------------------------------------------------------------------------
	// Get config file path
	static string GetConfigPath()
	{
		return CONFIG_PATH;
	}
}

// Data class must match the Workbench plugin output
class TW_LootTableConfig
{
	string Version;
	string GeneratedDate;
	int DefaultChance;
	int DefaultMaxCount;
	ref map<string, ref array<ref TW_GeneratedLootItem>> Categories;
}

class TW_GeneratedLootItem
{
	string resourceName;
	string displayName;
	int chanceToSpawn;
	int maxSpawnCount;
	bool isEnabled;
	int supplyCost;  // Arsenal supply cost - used to calculate spawn chance
}
