SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{687B576BBFAFDF2F}" {
   m_Info SCR_UIInfo "{687B576BBFAFDFCA}" {
    Name "Undead"
    Icon "{8653B0670349EFBC}UI/Textures/Editor/Toolbar/ToolbarAction_AttributesAdmin.edds"
   }
   m_Order 999
   m_LabelType UNDEAD
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}