SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{687B5768893CC8F1}" {
   m_sEntityPrefab "{67E76BA71804B965}622120A5448725E3/Prefabs/Groups/Group_Zombies_CIV.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{687B5768893CC888}" {
    }
    SCR_EntityCatalogSpawnerData "{687B5768893CC88A}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}