SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{687B5768837E9603}" {
   m_sEntityPrefab "{CF671E40479116ED}Prefabs/Characters/Core/Character_Base_Undead.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{687B5768837E960E}" {
    }
    SCR_EntityCatalogLoadoutData "{687B5768837E960D}" {
     m_fSpawnSupplyCost 0
    }
   }
  }
 }
}