SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 FactionKey "UNDEAD"
 FactionColor 0 0 0 1
 UIInfo SCR_FactionUIInfo "{56B49118D8D0A9C5}" {
  Name "Bacon Zombies"
  Icon "{8653B0670349EFBC}UI/Textures/Editor/Toolbar/ToolbarAction_AttributesAdmin.edds"
  m_sNameUpper "BACON ZOMBIES"
 }
 "Identity of soldiers" FactionIdentity "{60DCEDE56D10632C}" {
  VisualIdentityArray {
   VisualIdentity "{570EDB8787206B1C}" {
    Body "{409F523EA8450F74}622120A5448725E3/Assets/Character/BaseBody_LOD.et"
   }
  }
 }
 m_iOrder 1726667130
 m_OutlineFactionColor 0 0 0 1
 m_NotificationFactionColor 0 0 0 1
 m_NotificationTextFactionColor 0 0 0 1
 m_bIsMilitary 1
 m_sFactionFlag "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
 m_FactionLabel UNDEAD
 m_aFriendlyFactionsIds {
 }
 m_iFactionRadioFrequency 58000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{607A9A9FE55EDF5F}" : "{C41965420AB53CE7}Configs/EntityCatalog_Characters.conf" {
  }
  SCR_EntityCatalogMultiList "{6265160670A81736}" : "{748FCDF9C307FB27}Configs/EntityCatalog_Groups.conf" {
   m_aEntityEntryList {
    SCR_EntityCatalogEntry "{687B5768893CC8F1}" {
     m_sEntityPrefab "{64FD90593B949CD1}Prefabs/Groups/undeadCivGroup.et"
    }
   }
  }
 }
 m_sFactionBackground "{781301447441F404}UI/Textures/DeployMenu/Loadout-BG/Loadout_BG_Civilian.imageset"
}