SCR_MissionHeader {
 World "{27857FB5FF11B990}worlds/DatzNizla.ent"
 m_sName "DayZombiod"
 m_sAuthor "DeepRock"
 m_sDescription "DayZombiod"
 m_sDetails "DayZombiod"
 m_sIcon "{BE639AA0547BDB60}Assets/Gemini_Generated_Image_cllz1tcllz1tcllz.edds"
 m_sLoadingScreen "{BE639AA0547BDB60}Assets/Gemini_Generated_Image_cllz1tcllz1tcllz.edds"
 m_sPreviewImage "{BE639AA0547BDB60}Assets/Gemini_Generated_Image_cllz1tcllz1tcllz.edds"
 m_sGameMode "DayZombiod"
 m_iPlayerCount 128
 m_eEditableGameFlags 7
 m_eDefaultGameFlags 7
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_fDayTimeAcceleration 3
 m_fNightTimeAcceleration 9.6
 m_bRandomStartingWeather 1
 m_fXpMultiplier 0
}