SCR_MissionHeader {
 World "{2141020E2D2B68FB}worlds/GameMaster/Datz_Kunar.ent"
 m_sName "DayZombiod"
 m_sAuthor "DeepRock"
 m_sDescription "DayZombiod"
 m_sDetails "DayZombiod"
 m_sIcon "{2C4C8CAB6851A450}Assets/UI/generate-new-banner-iamge-the.edds"
 m_sLoadingScreen "{2C4C8CAB6851A450}Assets/UI/generate-new-banner-iamge-the.edds"
 m_sPreviewImage "{2C4C8CAB6851A450}Assets/UI/generate-new-banner-iamge-the.edds"
 m_sGameMode "DayZombiod"
 m_iPlayerCount 128
 m_eEditableGameFlags 7
 m_eDefaultGameFlags 7
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_fDayTimeAcceleration 3
 m_fNightTimeAcceleration 9.6
 m_bRandomStartingWeather 1
 m_fXpMultiplier 0
}